import { z, type ZodType } from "zod";

import {
  branchCreateSchema,
  branchHoursCreateSchema,
  branchHoursListSchema,
  branchHoursUpdateSchema,
  branchListSchema,
  branchUpdateSchema,
  businessBootstrapSchema,
  businessProfileUpdateSchema,
  businessSettingsUpdateSchema,
  currentBranchHoursSchema,
} from "../api/validators/business.validators.js";
import {
  branchServiceCreateSchema,
  branchServiceUpdateSchema,
  catalogListSchema,
  categoryCreateSchema,
  categoryListSchema,
  categoryUpdateSchema,
  packageCreateSchema,
  packageUpdateSchema,
  productCreateSchema,
  productUpdateSchema,
  serviceCreateSchema,
  serviceDetailSchema,
  serviceUpdateSchema,
} from "../api/validators/catalog.validators.js";
import {
  changePasswordSchema,
  confirmEmailSchema,
  customerRegistrationSchema,
  forgotPasswordSchema,
  googleLoginSchema,
  loginSchema,
  refreshTokenSchema,
  resetPasswordSchema,
} from "../validation/auth.schemas.js";
import {
  bookingListQuerySchema,
  cancelBookingBodySchema,
  cancelWaitlistBodySchema,
  createBookingBodySchema,
  createInquiryBodySchema,
  createQuoteBodySchema,
  createWaitlistBodySchema,
  employeeBookingListQuerySchema,
  externalSettlementBodySchema,
  inquiryListQuerySchema,
  offerWaitlistBodySchema,
  quoteActionBodySchema,
  rejectInquiryBodySchema,
  rescheduleBookingBodySchema,
  reviewInquiryBodySchema,
  scheduleAcceptedQuoteBodySchema,
  transitionBookingBodySchema,
  waitlistListQuerySchema,
} from "../validation/booking.schemas.js";
import {
  createCustomerBodySchema,
  customerListQuerySchema,
  updateCustomerBodySchema,
  updateMyCustomerProfileBodySchema,
} from "../validation/customer.schemas.js";
import {
  connectorBodySchema,
  connectorListQuerySchema,
  connectorStatusBodySchema,
  mappingBodySchema,
  mappingListQuerySchema,
  resolveMappingConflictBodySchema,
  syncJobBodySchema,
  syncJobListQuerySchema,
  updateConnectorBodySchema,
} from "../validation/integration.schemas.js";
import {
  notificationPreferenceBodySchema,
  notificationQueueListQuerySchema,
  notificationTemplateBodySchema,
  notificationTemplateListQuerySchema,
  pushSubscriptionBodySchema,
  updateNotificationTemplateBodySchema,
} from "../validation/notification.schemas.js";
import {
  auditLogListQuerySchema,
  outboxListQuerySchema,
} from "../validation/operations.schemas.js";
import {
  createAdvanceCheckoutBodySchema,
  customerPaymentListQuerySchema,
  paymentListQuerySchema,
  recordAdvanceBodySchema,
  recordRefundBodySchema,
  webhookEventListQuerySchema,
} from "../validation/payment.schemas.js";
import {
  availabilityQuerySchema,
  bookableResourceListQuerySchema,
  calendarBlockListQuerySchema,
  createBookableResourceBodySchema,
  createCalendarBlockBodySchema,
  createEmployeeScheduleBodySchema,
  createTimeOffBodySchema,
  myTimeOffListQuerySchema,
  scheduleListQuerySchema,
  staffTimeOffListQuerySchema,
  timeOffDecisionBodySchema,
  updateBookableResourceBodySchema,
  updateCalendarBlockBodySchema,
  updateEmployeeScheduleBodySchema,
} from "../validation/scheduling.schemas.js";
import {
  activeOnlyQuerySchema,
  adminListQuerySchema,
  createAdminBodySchema,
  createEmployeeBodySchema,
  createLevelBodySchema,
  createSkillBodySchema,
  employeeListQuerySchema,
  employeeServiceListQuerySchema,
  provisionEmployeeAccountBodySchema,
  staffAccessBodySchema,
  updateAdminBodySchema,
  updateEmployeeBodySchema,
  updateLevelBodySchema,
  updateMyEmployeeProfileBodySchema,
  updateSkillBodySchema,
  upsertEmployeeServiceBodySchema,
  upsertEmployeeSkillBodySchema,
} from "../validation/staff.schemas.js";

export type OpenApiSchema = Record<string, unknown>;

const convertZodSchema = (schema: ZodType): OpenApiSchema => {
  const converted = z.toJSONSchema(schema, {
    io: "input",
    unrepresentable: "any",
  }) as OpenApiSchema;
  delete converted.$schema;
  return converted;
};

/**
 * Runtime request validators are the source of truth for these components.
 * This keeps Swagger/Postman field constraints in lockstep with Express.
 */
const zodInputSchemas = {
  CustomerRegistrationInput: customerRegistrationSchema,
  LoginInput: loginSchema,
  GoogleLoginInput: googleLoginSchema,
  RefreshTokenInput: refreshTokenSchema,
  ChangePasswordInput: changePasswordSchema,
  ForgotPasswordInput: forgotPasswordSchema,
  ResetPasswordInput: resetPasswordSchema,
  ConfirmEmailInput: confirmEmailSchema,

  BranchListQuery: branchListSchema.shape.query,
  CurrentBranchHoursQuery: currentBranchHoursSchema.shape.query,
  BusinessBootstrapInput: businessBootstrapSchema.shape.body,
  BusinessProfileUpdateInput: businessProfileUpdateSchema.shape.body,
  BusinessSettingsUpdateInput: businessSettingsUpdateSchema.shape.body,
  BranchCreateInput: branchCreateSchema.shape.body,
  BranchUpdateInput: branchUpdateSchema.shape.body,
  BranchHoursListQuery: branchHoursListSchema.shape.query,
  BranchHoursCreateInput: branchHoursCreateSchema.shape.body,
  BranchHoursUpdateInput: branchHoursUpdateSchema.shape.body,

  CategoryListQuery: categoryListSchema.shape.query,
  CatalogListQuery: catalogListSchema.shape.query,
  ServiceDetailQuery: serviceDetailSchema.shape.query,
  CategoryCreateInput: categoryCreateSchema.shape.body,
  CategoryUpdateInput: categoryUpdateSchema.shape.body,
  ServiceCreateInput: serviceCreateSchema.shape.body,
  ServiceUpdateInput: serviceUpdateSchema.shape.body,
  ProductCreateInput: productCreateSchema.shape.body,
  ProductUpdateInput: productUpdateSchema.shape.body,
  PackageCreateInput: packageCreateSchema.shape.body,
  PackageUpdateInput: packageUpdateSchema.shape.body,
  BranchServiceCreateInput: branchServiceCreateSchema.shape.body,
  BranchServiceUpdateInput: branchServiceUpdateSchema.shape.body,

  CustomerListQuery: customerListQuerySchema,
  CustomerCreateInput: createCustomerBodySchema,
  CustomerUpdateInput: updateCustomerBodySchema,
  MyCustomerProfileUpdateInput: updateMyCustomerProfileBodySchema,

  BookingListQuery: bookingListQuerySchema,
  EmployeeBookingListQuery: employeeBookingListQuerySchema,
  BookingCreateInput: createBookingBodySchema,
  BookingCancelInput: cancelBookingBodySchema,
  BookingRescheduleInput: rescheduleBookingBodySchema,
  BookingTransitionInput: transitionBookingBodySchema,
  ExternalSettlementInput: externalSettlementBodySchema,
  WaitlistListQuery: waitlistListQuerySchema,
  WaitlistCreateInput: createWaitlistBodySchema,
  WaitlistCancelInput: cancelWaitlistBodySchema,
  WaitlistOfferInput: offerWaitlistBodySchema,
  InquiryListQuery: inquiryListQuerySchema,
  InquiryCreateInput: createInquiryBodySchema,
  InquiryReviewInput: reviewInquiryBodySchema,
  InquiryRejectInput: rejectInquiryBodySchema,
  QuoteCreateInput: createQuoteBodySchema,
  QuoteActionInput: quoteActionBodySchema,
  AcceptedQuoteScheduleInput: scheduleAcceptedQuoteBodySchema,

  EmployeeListQuery: employeeListQuerySchema,
  EmployeeCreateInput: createEmployeeBodySchema,
  EmployeeUpdateInput: updateEmployeeBodySchema,
  MyEmployeeProfileUpdateInput: updateMyEmployeeProfileBodySchema,
  EmployeeAccountProvisionInput: provisionEmployeeAccountBodySchema,
  StaffAccessInput: staffAccessBodySchema,
  EmployeeServiceListQuery: employeeServiceListQuerySchema,
  EmployeeSkillUpsertInput: upsertEmployeeSkillBodySchema,
  EmployeeServiceUpsertInput: upsertEmployeeServiceBodySchema,
  ActiveOnlyQuery: activeOnlyQuerySchema,
  SkillCreateInput: createSkillBodySchema,
  SkillUpdateInput: updateSkillBodySchema,
  EmployeeLevelCreateInput: createLevelBodySchema,
  EmployeeLevelUpdateInput: updateLevelBodySchema,
  AdminListQuery: adminListQuerySchema,
  AdminCreateInput: createAdminBodySchema,
  AdminUpdateInput: updateAdminBodySchema,

  EmployeeScheduleListQuery: scheduleListQuerySchema,
  EmployeeScheduleCreateInput: createEmployeeScheduleBodySchema,
  EmployeeScheduleUpdateInput: updateEmployeeScheduleBodySchema,
  MyTimeOffListQuery: myTimeOffListQuerySchema,
  StaffTimeOffListQuery: staffTimeOffListQuerySchema,
  TimeOffCreateInput: createTimeOffBodySchema,
  TimeOffDecisionInput: timeOffDecisionBodySchema,
  CalendarBlockListQuery: calendarBlockListQuerySchema,
  CalendarBlockCreateInput: createCalendarBlockBodySchema,
  CalendarBlockUpdateInput: updateCalendarBlockBodySchema,
  BookableResourceListQuery: bookableResourceListQuerySchema,
  BookableResourceCreateInput: createBookableResourceBodySchema,
  BookableResourceUpdateInput: updateBookableResourceBodySchema,
  AvailabilityQuery: availabilityQuerySchema,

  CustomerPaymentListQuery: customerPaymentListQuerySchema,
  StaffPaymentListQuery: paymentListQuerySchema,
  PaymentWebhookEventListQuery: webhookEventListQuerySchema,
  AdvanceCheckoutCreateInput: createAdvanceCheckoutBodySchema,
  AdvanceRecordInput: recordAdvanceBodySchema,
  RefundRecordInput: recordRefundBodySchema,

  NotificationPreferenceUpdateInput: notificationPreferenceBodySchema,
  PushSubscriptionCreateInput: pushSubscriptionBodySchema,
  NotificationQueueListQuery: notificationQueueListQuerySchema,
  NotificationTemplateListQuery: notificationTemplateListQuerySchema,
  NotificationTemplateCreateInput: notificationTemplateBodySchema,
  NotificationTemplateUpdateInput: updateNotificationTemplateBodySchema,

  ConnectorListQuery: connectorListQuerySchema,
  ConnectorCreateInput: connectorBodySchema,
  ConnectorUpdateInput: updateConnectorBodySchema,
  ConnectorStatusInput: connectorStatusBodySchema,
  MappingListQuery: mappingListQuerySchema,
  MappingUpsertInput: mappingBodySchema,
  MappingConflictResolutionInput: resolveMappingConflictBodySchema,
  SyncJobListQuery: syncJobListQuerySchema,
  SyncJobCreateInput: syncJobBodySchema,
  AuditLogListQuery: auditLogListQuerySchema,
  OutboxListQuery: outboxListQuerySchema,
} satisfies Record<string, ZodType>;

export type InputSchemaName = keyof typeof zodInputSchemas;

export const inputSchemas = Object.fromEntries(
  Object.entries(zodInputSchemas).map(([name, schema]) => [
    name,
    convertZodSchema(schema),
  ]),
) as Record<InputSchemaName, OpenApiSchema>;

const objectId = {
  type: "string",
  pattern: "^[a-fA-F0-9]{24}$",
  example: "66a8f2d4e32ca95652a73f11",
};
const dateTime = { type: "string", format: "date-time" };
const localDate = {
  type: "string",
  format: "date",
  pattern: "^\\d{4}-\\d{2}-\\d{2}$",
};
const nullable = (schema: OpenApiSchema): OpenApiSchema => ({
  anyOf: [schema, { type: "null" }],
});
const ref = (name: string): OpenApiSchema => ({
  $ref: `#/components/schemas/${name}`,
});
const arrayOf = (items: OpenApiSchema): OpenApiSchema => ({
  type: "array",
  items,
});
const enumString = (values: readonly string[]): OpenApiSchema => ({
  type: "string",
  enum: values,
});
const documentSchema = (
  properties: Record<string, OpenApiSchema>,
  required: string[],
): OpenApiSchema => ({
  type: "object",
  properties: {
    _id: objectId,
    ...properties,
    createdAt: dateTime,
    updatedAt: dateTime,
  },
  required: ["_id", ...required, "createdAt", "updatedAt"],
  additionalProperties: false,
});

const priceSchema: OpenApiSchema = {
  type: "object",
  properties: {
    mode: enumString(["fixed", "starting_from", "range", "quote_required"]),
    currency: { type: "string", pattern: "^[A-Z]{3}$", example: "LKR" },
    amountMinor: { type: "integer", minimum: 0 },
    fromAmountMinor: { type: "integer", minimum: 0 },
    toAmountMinor: { type: "integer", minimum: 0 },
    label: { type: "string", maxLength: 120 },
  },
  required: ["mode", "currency"],
  additionalProperties: false,
};

const durationSchema: OpenApiSchema = {
  type: "object",
  properties: {
    applicationMinutes: { type: "integer", minimum: 0 },
    processingMinutes: { type: "integer", minimum: 0 },
    finishingMinutes: { type: "integer", minimum: 0 },
    bufferMinutes: { type: "integer", minimum: 0 },
    processingBlocksEmployee: { type: "boolean" },
  },
  required: [
    "applicationMinutes",
    "processingMinutes",
    "finishingMinutes",
    "bufferMinutes",
    "processingBlocksEmployee",
  ],
  additionalProperties: false,
};

const advancePolicySchema: OpenApiSchema = {
  type: "object",
  properties: {
    requirement: enumString(["none", "optional", "required"]),
    calculation: enumString(["none", "fixed", "percentage"]),
    fixedAmountMinor: { type: "integer", minimum: 0 },
    percentage: { type: "number", minimum: 0, maximum: 100 },
    basis: enumString(["estimate", "accepted_quote"]),
  },
  required: ["requirement", "calculation", "basis"],
  additionalProperties: false,
};

const timeIntervalSchema: OpenApiSchema = {
  type: "object",
  properties: {
    start: { type: "string", pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d$" },
    end: { type: "string", pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d$" },
  },
  required: ["start", "end"],
  additionalProperties: false,
};

const userSchema = {
  type: "object",
  properties: {
    id: { type: "string", pattern: "^[a-fA-F0-9]{24}$" },
    name: { type: "string" },
    email: { type: "string", format: "email" },
    phone: { type: "string", pattern: "^\\+[1-9]\\d{7,14}$" },
    role: enumString(["admin", "employee", "customer"]),
    authMethods: arrayOf(enumString(["local", "google"])),
    avatarUrl: { type: "string", format: "uri" },
    isActive: { type: "boolean" },
    emailVerifiedAt: dateTime,
    phoneVerifiedAt: dateTime,
    lastLoginAt: dateTime,
    createdAt: dateTime,
    updatedAt: dateTime,
  },
  required: ["id", "name", "role", "authMethods", "isActive", "createdAt", "updatedAt"],
  additionalProperties: false,
} satisfies OpenApiSchema;

const staffPermissions = [
  "manage_business",
  "manage_settings",
  "manage_branches",
  "manage_catalog",
  "view_customers",
  "manage_customers",
  "manage_staff",
  "manage_schedules",
  "manage_bookings",
  "view_booking_payments",
  "manage_notifications",
  "manage_integrations",
] as const;

export const responseSchemas: Record<string, OpenApiSchema> = {
  Address: {
    type: "object",
    properties: {
      line1: { type: "string" },
      line2: { type: "string" },
      city: { type: "string" },
      state: { type: "string" },
      postalCode: { type: "string" },
      countryCode: { type: "string", minLength: 2, maxLength: 2 },
    },
    additionalProperties: false,
  },
  PricePresentation: priceSchema,
  ServiceDuration: durationSchema,
  AdvancePolicy: advancePolicySchema,
  TimeInterval: timeIntervalSchema,
  PublicUser: userSchema,
  User: documentSchema(
    {
      name: { type: "string" },
      email: { type: "string", format: "email" },
      phone: { type: "string" },
      authMethods: arrayOf(enumString(["local", "google"])),
      role: enumString(["admin", "employee", "customer"]),
      avatarUrl: { type: "string", format: "uri" },
      isActive: { type: "boolean" },
      emailVerifiedAt: dateTime,
      phoneVerifiedAt: dateTime,
      lastLoginAt: dateTime,
      passwordChangedAt: dateTime,
    },
    ["name", "authMethods", "role", "isActive"],
  ),
  AuthResult: {
    type: "object",
    properties: {
      user: ref("PublicUser"),
      authentication: {
        type: "object",
        properties: {
          accessToken: { type: "string" },
          tokenType: { type: "string", const: "Bearer" },
          expiresIn: { type: "integer", minimum: 1 },
          refreshExpiresIn: { type: "integer", minimum: 1 },
          csrfToken: { type: "string" },
          refreshToken: {
            type: "string",
            description: "Returned only when AUTH_RETURN_REFRESH_TOKEN=true.",
          },
        },
        required: ["accessToken", "tokenType", "expiresIn", "refreshExpiresIn", "csrfToken"],
        additionalProperties: false,
      },
    },
    required: ["user", "authentication"],
    additionalProperties: false,
  },
  AuthSession: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      current: { type: "boolean" },
      createdAt: dateTime,
      expiresAt: dateTime,
      userAgent: { type: "string" },
    },
    required: ["id", "current", "createdAt", "expiresAt"],
    additionalProperties: false,
  },
  AuthActionResult: {
    type: "object",
    properties: {
      message: { type: "string" },
      alreadyVerified: { type: "boolean" },
      devToken: {
        type: "string",
        description: "Development-only action token; never returned in production.",
      },
    },
    required: ["message"],
    additionalProperties: false,
  },
  BusinessProfile: documentSchema(
    {
      singletonKey: { type: "string", const: "default" },
      name: { type: "string" },
      legalName: { type: "string" },
      slug: { type: "string" },
      status: enumString(["active", "inactive", "closed"]),
      email: { type: "string", format: "email" },
      phone: { type: "string" },
      websiteUrl: { type: "string", format: "uri" },
      logoUrl: { type: "string", format: "uri" },
      registeredAddress: ref("Address"),
    },
    ["singletonKey", "name", "slug", "status"],
  ),
  BusinessSettings: documentSchema(
    {
      singletonKey: { type: "string", const: "default" },
      branchMode: enumString(["single", "multiple"]),
      primaryBranchId: objectId,
      locale: { type: "string" },
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
      finalPaymentHandling: enumString(["at_salon", "external_system"]),
      booking: {
        type: "object",
        properties: {
          slotIntervalMinutes: { type: "integer" },
          minimumNoticeMinutes: { type: "integer" },
          maximumAdvanceDays: { type: "integer" },
          temporaryHoldMinutes: { type: "integer" },
          cancellationWindowHours: { type: "integer" },
          allowWalkIns: { type: "boolean" },
          allowWaitlist: { type: "boolean" },
          allowProcessingOverlap: { type: "boolean" },
        },
        additionalProperties: false,
      },
      customerAuth: {
        type: "object",
        properties: {
          emailPasswordEnabled: { type: "boolean" },
          phonePasswordEnabled: { type: "boolean" },
          googleEnabled: { type: "boolean" },
        },
        additionalProperties: false,
      },
      defaultAdvance: ref("AdvancePolicy"),
      reminders: {
        type: "object",
        properties: {
          enabled: { type: "boolean" },
          leadMinutes: arrayOf({ type: "integer", minimum: 1 }),
          channels: arrayOf(enumString(["email", "sms", "whatsapp", "push"])),
        },
        additionalProperties: false,
      },
    },
    ["singletonKey", "branchMode", "primaryBranchId", "locale", "currency", "finalPaymentHandling", "booking", "customerAuth", "defaultAdvance", "reminders"],
  ),
  Branch: documentSchema(
    {
      name: { type: "string" },
      code: { type: "string" },
      email: { type: "string", format: "email" },
      phone: { type: "string" },
      address: ref("Address"),
      isPrimary: { type: "boolean" },
      isActive: { type: "boolean" },
      bookingsEnabled: { type: "boolean" },
    },
    ["name", "code", "isPrimary", "isActive", "bookingsEnabled"],
  ),
  BranchHours: documentSchema(
    {
      branchId: objectId,
      name: { type: "string" },
      effectiveFrom: localDate,
      effectiveUntil: nullable(localDate),
      days: arrayOf({
        type: "object",
        properties: {
          dayOfWeek: { type: "integer", minimum: 0, maximum: 6 },
          isClosed: { type: "boolean" },
          intervals: arrayOf(ref("TimeInterval")),
        },
        required: ["dayOfWeek", "isClosed", "intervals"],
        additionalProperties: false,
      }),
      status: enumString(["draft", "active", "archived"]),
    },
    ["branchId", "name", "effectiveFrom", "days", "status"],
  ),
  PublicBranchHours: {
    type: "object",
    properties: {
      branch: ref("Branch"),
      hours: nullable(ref("BranchHours")),
      effectiveOn: localDate,
    },
    required: ["branch", "hours", "effectiveOn"],
    additionalProperties: false,
  },
  BusinessBootstrapResult: {
    type: "object",
    properties: {
      profile: ref("BusinessProfile"),
      branch: ref("Branch"),
      settings: ref("BusinessSettings"),
    },
    required: ["profile", "branch", "settings"],
    additionalProperties: false,
  },
  BusinessOverview: {
    type: "object",
    properties: {
      profile: ref("BusinessProfile"),
      settings: nullable(ref("BusinessSettings")),
      branches: arrayOf(ref("Branch")),
    },
    required: ["profile", "branches"],
    additionalProperties: false,
  },
  CatalogCategory: documentSchema(
    {
      parentId: nullable(objectId),
      name: { type: "string" },
      slug: { type: "string" },
      description: { type: "string" },
      appliesTo: arrayOf(enumString(["service", "product", "package"])),
      sortOrder: { type: "integer", minimum: 0 },
      isActive: { type: "boolean" },
    },
    ["name", "slug", "appliesTo", "sortOrder", "isActive"],
  ),
  Service: documentSchema(
    {
      categoryId: objectId,
      code: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      description: { type: "string" },
      targetClientGender: enumString(["male", "female", "all"]),
      requiredSkillIds: arrayOf(objectId),
      duration: ref("ServiceDuration"),
      price: ref("PricePresentation"),
      tierPrices: arrayOf({
        type: "object",
        properties: { employeeLevelId: objectId, price: ref("PricePresentation") },
        required: ["employeeLevelId", "price"],
        additionalProperties: false,
      }),
      advancePolicy: nullable(ref("AdvancePolicy")),
      bookingMode: enumString(["instant", "request", "consultation_required"]),
      isActive: { type: "boolean" },
      isOnlineBookable: { type: "boolean" },
      sortOrder: { type: "integer" },
      branchService: nullable(ref("BranchService")),
    },
    ["categoryId", "code", "name", "slug", "targetClientGender", "requiredSkillIds", "duration", "price", "tierPrices", "bookingMode", "isActive", "isOnlineBookable", "sortOrder"],
  ),
  Product: documentSchema(
    {
      categoryId: objectId,
      branchIds: arrayOf(objectId),
      availableAtAllBranches: { type: "boolean" },
      code: { type: "string" },
      sku: { type: "string" },
      barcode: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      brand: { type: "string" },
      description: { type: "string" },
      imageUrls: arrayOf({ type: "string", format: "uri" }),
      price: ref("PricePresentation"),
      purchaseMode: enumString(["in_store", "external_link", "inquiry"]),
      externalPurchaseUrl: { type: "string", format: "uri" },
      isActive: { type: "boolean" },
      isPublished: { type: "boolean" },
      sortOrder: { type: "integer" },
    },
    ["categoryId", "branchIds", "availableAtAllBranches", "code", "name", "slug", "imageUrls", "price", "purchaseMode", "isActive", "isPublished", "sortOrder"],
  ),
  ServicePackage: documentSchema(
    {
      categoryId: objectId,
      branchIds: arrayOf(objectId),
      availableAtAllBranches: { type: "boolean" },
      code: { type: "string" },
      name: { type: "string" },
      slug: { type: "string" },
      description: { type: "string" },
      kind: enumString(["bundle", "wedding", "event"]),
      bookingMode: enumString(["request_quote", "consultation_required"]),
      minimumPartySize: { type: "integer" },
      maximumPartySize: nullable({ type: "integer" }),
      allowsOffsite: { type: "boolean" },
      travelMinutesBefore: { type: "integer" },
      travelMinutesAfter: { type: "integer" },
      serviceComponents: arrayOf({
        type: "object",
        properties: { serviceId: objectId, quantity: { type: "integer" }, isOptional: { type: "boolean" } },
        required: ["serviceId", "quantity", "isOptional"],
        additionalProperties: false,
      }),
      productInclusions: arrayOf({
        type: "object",
        properties: { productId: objectId, quantity: { type: "integer" }, isOptional: { type: "boolean" } },
        required: ["productId", "quantity", "isOptional"],
        additionalProperties: false,
      }),
      price: ref("PricePresentation"),
      advancePolicy: nullable(ref("AdvancePolicy")),
      isActive: { type: "boolean" },
      isPublished: { type: "boolean" },
      sortOrder: { type: "integer" },
    },
    ["categoryId", "branchIds", "availableAtAllBranches", "code", "name", "slug", "kind", "bookingMode", "minimumPartySize", "allowsOffsite", "travelMinutesBefore", "travelMinutesAfter", "serviceComponents", "productInclusions", "price", "isActive", "isPublished", "sortOrder"],
  ),
  BranchService: documentSchema(
    {
      branchId: objectId,
      serviceId: objectId,
      priceOverride: nullable(ref("PricePresentation")),
      durationOverride: nullable(ref("ServiceDuration")),
      advancePolicyOverride: nullable(ref("AdvancePolicy")),
      isActive: { type: "boolean" },
      isOnlineBookable: { type: "boolean" },
    },
    ["branchId", "serviceId", "isActive", "isOnlineBookable"],
  ),
  Customer: documentSchema(
    {
      userId: nullable(objectId),
      name: { type: "string" },
      preferredName: nullable({ type: "string" }),
      email: nullable({ type: "string", format: "email" }),
      phone: nullable({ type: "string" }),
      gender: enumString(["male", "female", "non_binary", "prefer_not_to_say", "unspecified"]),
      dateOfBirth: nullable(localDate),
      preferredBranchId: nullable(objectId),
      preferredEmployeeId: nullable(objectId),
      tags: arrayOf({ type: "string" }),
      internalNotes: nullable({ type: "string", description: "Staff views only." }),
      source: enumString(["online", "admin", "walk_in", "erp_import", "api"]),
      status: enumString(["active", "blocked", "archived"]),
      createdByUserId: objectId,
    },
    ["name", "gender", "tags", "source", "status"],
  ),
  StaffAccess: documentSchema(
    {
      userId: objectId,
      permissions: arrayOf(enumString(staffPermissions)),
      allBranches: { type: "boolean" },
      branchIds: arrayOf(objectId),
      requiredAuthMethod: { type: "string", const: "local" },
      status: enumString(["invited", "active", "suspended", "revoked"]),
      invitedByUserId: objectId,
      joinedAt: dateTime,
    },
    ["userId", "permissions", "allBranches", "branchIds", "requiredAuthMethod", "status"],
  ),
  AdminProfile: {
    type: "object",
    properties: {
      admin: ref("User"),
      access: nullable(ref("StaffAccess")),
    },
    required: ["admin", "access"],
    additionalProperties: false,
  },
  AdminListItem: {
    allOf: [
      ref("User"),
      {
        type: "object",
        properties: { access: nullable(ref("StaffAccess")) },
        required: ["access"],
      },
    ],
  },
  Employee: documentSchema(
    {
      userId: nullable(objectId),
      employeeCode: { type: "string" },
      name: { type: "string" },
      title: nullable({ type: "string" }),
      levelId: nullable(objectId),
      workEmail: nullable({ type: "string", format: "email" }),
      workPhone: nullable({ type: "string" }),
      branchIds: arrayOf(objectId),
      primaryBranchId: nullable(objectId),
      employmentType: enumString(["full_time", "part_time", "contractor", "temporary"]),
      status: enumString(["invited", "active", "on_leave", "inactive", "terminated"]),
      isBookable: { type: "boolean" },
      acceptsOnlineBookings: { type: "boolean" },
      servesClientGender: enumString(["male", "female", "all"]),
      maxConcurrentClients: { type: "integer", minimum: 1, maximum: 5 },
      bio: nullable({ type: "string" }),
      avatarUrl: nullable({ type: "string", format: "uri" }),
      calendarColor: { type: "string", pattern: "^#[0-9A-F]{6}$" },
      hireDate: nullable(localDate),
      terminationDate: nullable(localDate),
      access: ref("StaffAccess"),
    },
    ["employeeCode", "name", "branchIds", "employmentType", "status", "isBookable", "acceptsOnlineBookings", "servesClientGender", "maxConcurrentClients", "calendarColor"],
  ),
  EmployeeProfile: {
    type: "object",
    properties: {
      employee: ref("Employee"),
      account: nullable(ref("User")),
      access: nullable(ref("StaffAccess")),
      skills: arrayOf(ref("EmployeeSkill")),
      services: arrayOf(ref("EmployeeService")),
    },
    required: ["employee", "account", "access", "skills", "services"],
    additionalProperties: false,
  },
  EmployeeSkill: documentSchema(
    {
      employeeId: objectId,
      skillId: objectId,
      proficiency: enumString(["trainee", "qualified", "advanced", "expert"]),
      certifiedAt: nullable(localDate),
      expiresAt: nullable(localDate),
      isActive: { type: "boolean" },
    },
    ["employeeId", "skillId", "proficiency", "isActive"],
  ),
  EmployeeService: documentSchema(
    {
      branchId: objectId,
      employeeId: objectId,
      serviceId: objectId,
      proficiency: enumString(["trainee", "qualified", "advanced", "expert"]),
      priceOverride: nullable(ref("PricePresentation")),
      durationOverride: nullable(ref("ServiceDuration")),
      servesClientGenderOverride: nullable(enumString(["male", "female", "all"])),
      isActive: { type: "boolean" },
      isOnlineBookable: { type: "boolean" },
      validFrom: nullable(localDate),
      validUntil: nullable(localDate),
    },
    ["branchId", "employeeId", "serviceId", "proficiency", "isActive", "isOnlineBookable"],
  ),
  Skill: documentSchema(
    { name: { type: "string" }, code: { type: "string" }, description: nullable({ type: "string" }), isActive: { type: "boolean" } },
    ["name", "code", "isActive"],
  ),
  EmployeeLevel: documentSchema(
    { name: { type: "string" }, code: { type: "string" }, rank: { type: "integer" }, isActive: { type: "boolean" } },
    ["name", "code", "rank", "isActive"],
  ),
  BookingItem: documentSchema(
    {
      branchId: objectId,
      bookingId: objectId,
      quoteLineId: objectId,
      packageId: objectId,
      sequence: { type: "integer" },
      serviceId: objectId,
      employeeId: objectId,
      serviceSnapshot: { type: "object", additionalProperties: true },
      employeeSnapshot: { type: "object", additionalProperties: true },
      phases: arrayOf({
        type: "object",
        properties: {
          key: { type: "string" },
          type: enumString(["application", "processing", "finishing", "buffer", "travel"]),
          startAt: dateTime,
          endAt: dateTime,
          blocksEmployee: { type: "boolean" },
          blocksBranch: { type: "boolean" },
        },
        additionalProperties: false,
      }),
      startAt: dateTime,
      endAt: dateTime,
      priceSnapshot: { type: "object", additionalProperties: true },
      status: enumString(["requested", "pending_advance", "confirmed", "checked_in", "in_progress", "completed", "cancelled", "no_show"]),
    },
    ["branchId", "bookingId", "sequence", "serviceId", "employeeId", "serviceSnapshot", "employeeSnapshot", "phases", "startAt", "endAt", "priceSnapshot", "status"],
  ),
  Booking: documentSchema(
    {
      branchId: objectId,
      customerId: objectId,
      employeeIds: arrayOf(objectId),
      quoteId: objectId,
      packageId: objectId,
      packageSnapshot: { type: "object", additionalProperties: true },
      reference: { type: "string" },
      source: enumString(["online", "admin", "walk_in", "api", "external"]),
      status: enumString(["requested", "pending_advance", "confirmed", "checked_in", "in_progress", "completed", "cancelled", "no_show"]),
      startAt: dateTime,
      endAt: dateTime,
      customerSnapshot: { type: "object", additionalProperties: true },
      pricingSnapshot: { type: "object", additionalProperties: true },
      externalSettlement: { type: "object", additionalProperties: true },
      includedProductSnapshots: arrayOf({ type: "object", additionalProperties: true }),
      reservationCountSnapshot: { type: "integer" },
      cancellationPolicySnapshot: { type: "object", additionalProperties: true },
      event: { type: "object", additionalProperties: true },
      customerNote: { type: "string" },
      internalNote: { type: "string", description: "Staff views only." },
      expiresAt: dateTime,
      confirmedAt: dateTime,
      checkedInAt: dateTime,
      completedAt: dateTime,
      cancelledAt: dateTime,
      cancellationReason: { type: "string" },
      createdByUserId: objectId,
      updatedByUserId: objectId,
      items: arrayOf(ref("BookingItem")),
      holdExpired: { type: "boolean" },
    },
    ["branchId", "customerId", "reference", "source", "status", "startAt", "endAt", "customerSnapshot", "pricingSnapshot", "externalSettlement", "includedProductSnapshots", "cancellationPolicySnapshot", "event", "items", "holdExpired"],
  ),
  WaitlistEntry: documentSchema(
    {
      branchId: objectId,
      customerId: objectId,
      serviceIds: arrayOf(objectId),
      preferredEmployeeIds: arrayOf(objectId),
      windowStartAt: dateTime,
      windowEndAt: dateTime,
      requiredMinutes: { type: "integer" },
      partySize: { type: "integer" },
      priority: { type: "integer" },
      source: enumString(["online", "admin", "walk_in"]),
      status: enumString(["waiting", "offered", "booked", "expired", "cancelled"]),
      offeredUntil: dateTime,
      bookingId: objectId,
      note: { type: "string" },
    },
    ["branchId", "customerId", "serviceIds", "preferredEmployeeIds", "windowStartAt", "windowEndAt", "requiredMinutes", "partySize", "priority", "source", "status"],
  ),
  BookingQuote: documentSchema(
    {
      inquiryId: objectId,
      revision: { type: "integer" },
      status: enumString(["draft", "sent", "accepted", "rejected", "expired", "superseded"]),
      validUntil: dateTime,
      branchId: objectId,
      proposedStartAt: dateTime,
      proposedEndAt: dateTime,
      travelMinutesBefore: { type: "integer" },
      travelMinutesAfter: { type: "integer" },
      currency: { type: "string" },
      lines: arrayOf({ type: "object", additionalProperties: true }),
      quotedTotalMinor: { type: "integer" },
      advanceRequirement: enumString(["none", "optional", "required"]),
      advanceDueMinor: { type: "integer" },
      terms: { type: "string" },
      sentAt: dateTime,
      acceptedAt: dateTime,
      createdByUserId: objectId,
    },
    ["inquiryId", "revision", "status", "validUntil", "branchId", "travelMinutesBefore", "travelMinutesAfter", "currency", "lines", "quotedTotalMinor", "advanceRequirement", "advanceDueMinor", "createdByUserId"],
  ),
  BookingInquiry: documentSchema(
    {
      customerId: objectId,
      branchId: objectId,
      packageId: objectId,
      serviceIds: arrayOf(objectId),
      productIds: arrayOf(objectId),
      type: enumString(["service", "product", "package", "wedding", "event"]),
      preferredDateFrom: localDate,
      preferredDateTo: localDate,
      partySize: { type: "integer" },
      offsite: { type: "boolean" },
      venueAddress: { type: "string" },
      customerNote: { type: "string" },
      internalNote: { type: "string", description: "Staff views only." },
      status: enumString(["new", "reviewing", "quoted", "accepted", "declined", "expired", "cancelled"]),
      assignedToUserId: objectId,
      quotes: arrayOf(ref("BookingQuote")),
    },
    ["customerId", "serviceIds", "productIds", "type", "partySize", "offsite", "status"],
  ),
  EmployeeSchedule: documentSchema(
    {
      branchId: objectId,
      employeeId: objectId,
      name: { type: "string" },
      effectiveFrom: localDate,
      effectiveUntil: nullable(localDate),
      days: arrayOf({
        type: "object",
        properties: { dayOfWeek: { type: "integer", minimum: 0, maximum: 6 }, shifts: arrayOf(ref("TimeInterval")), breaks: arrayOf(ref("TimeInterval")) },
        required: ["dayOfWeek", "shifts", "breaks"],
        additionalProperties: false,
      }),
      status: enumString(["draft", "active", "archived"]),
    },
    ["branchId", "employeeId", "name", "effectiveFrom", "days", "status"],
  ),
  TimeOff: documentSchema(
    {
      employeeId: objectId,
      allBranches: { type: "boolean" },
      branchIds: arrayOf(objectId),
      type: enumString(["vacation", "sick", "personal", "unpaid", "other"]),
      startAt: dateTime,
      endAt: dateTime,
      allDay: { type: "boolean" },
      status: enumString(["requested", "approved", "rejected", "cancelled"]),
      reason: { type: "string" },
      privateNote: { type: "string", description: "Staff decision views only." },
      requestedByUserId: objectId,
      decidedByUserId: objectId,
      decidedAt: dateTime,
    },
    ["employeeId", "allBranches", "branchIds", "type", "startAt", "endAt", "allDay", "status"],
  ),
  CalendarBlock: documentSchema(
    {
      branchId: objectId,
      employeeId: nullable(objectId),
      type: enumString(["branch_closed", "break", "meeting", "training", "maintenance", "travel", "manual", "other"]),
      source: enumString(["manual", "time_off", "booking", "holiday", "integration"]),
      sourceId: objectId,
      title: { type: "string" },
      note: nullable({ type: "string" }),
      startAt: dateTime,
      endAt: dateTime,
      allDay: { type: "boolean" },
      blocksBookings: { type: "boolean" },
      status: enumString(["active", "cancelled"]),
      createdByUserId: objectId,
    },
    ["branchId", "type", "source", "title", "startAt", "endAt", "allDay", "blocksBookings", "status"],
  ),
  BookableResource: documentSchema(
    {
      branchId: objectId,
      type: enumString(["chair", "room", "equipment"]),
      code: { type: "string" },
      name: { type: "string" },
      capacity: { type: "integer" },
      serviceIds: arrayOf(objectId),
      isActive: { type: "boolean" },
    },
    ["branchId", "type", "code", "name", "capacity", "serviceIds", "isActive"],
  ),
  Availability: {
    type: "object",
    properties: {
      branchId: objectId,
      service: {
        type: "object",
        properties: { id: objectId, name: { type: "string" }, bookingMode: enumString(["instant", "request"]) },
        required: ["id", "name", "bookingMode"],
        additionalProperties: false,
      },
      date: localDate,
      timeZone: { type: "string", example: "Asia/Colombo" },
      generatedAt: dateTime,
      employees: arrayOf({
        type: "object",
        properties: {
          employee: {
            type: "object",
            properties: { id: objectId, name: { type: "string" }, title: { type: "string" }, avatarUrl: { type: "string", format: "uri" } },
            required: ["id", "name"],
            additionalProperties: false,
          },
          slots: arrayOf({
            type: "object",
            properties: { startAt: dateTime, endAt: dateTime, duration: ref("ServiceDuration"), price: ref("PricePresentation"), phases: arrayOf({ type: "object", additionalProperties: true }) },
            required: ["startAt", "endAt", "duration", "price", "phases"],
            additionalProperties: false,
          }),
        },
        required: ["employee", "slots"],
        additionalProperties: false,
      }),
      totalSlots: { type: "integer", minimum: 0 },
    },
    required: ["branchId", "service", "date", "timeZone", "generatedAt", "employees", "totalSlots"],
    additionalProperties: false,
  },
  BookingPayment: documentSchema(
    {
      branchId: objectId,
      bookingId: objectId,
      customerId: objectId,
      purpose: enumString(["advance", "advance_refund", "cancellation_fee", "no_show_fee"]),
      provider: { type: "string" },
      providerCheckoutId: { type: "string" },
      checkoutExpiresAt: dateTime,
      amountMinor: { type: "integer" },
      currency: { type: "string" },
      status: enumString(["pending", "authorized", "succeeded", "failed", "cancelled", "refunded"]),
      paymentMethodType: enumString(["card", "bank_transfer", "cash", "wallet", "external"]),
      relatedPaymentId: objectId,
      failureCode: { type: "string" },
      failureMessage: { type: "string" },
      processedAt: dateTime,
      checkout: {
        type: "object",
        properties: { url: { type: "string", format: "uri" }, clientSecret: { type: "string" }, expiresAt: dateTime },
        additionalProperties: true,
      },
    },
    ["branchId", "bookingId", "customerId", "purpose", "provider", "amountMinor", "currency", "status"],
  ),
  AdvanceCheckout: {
    type: "object",
    properties: {
      provider: { type: "string" },
      checkoutId: { type: "string" },
      checkoutUrl: { type: "string", format: "uri" },
      clientToken: { type: "string" },
      expiresAt: dateTime,
      bookingId: objectId,
      amountMinor: { type: "integer", minimum: 1 },
      currency: { type: "string", pattern: "^[A-Z]{3}$" },
    },
    required: ["provider", "checkoutId", "expiresAt", "bookingId", "amountMinor", "currency"],
    additionalProperties: false,
  },
  PaymentWebhookEvent: documentSchema(
    {
      provider: { type: "string" },
      merchantAccountId: { type: "string" },
      providerEventId: { type: "string" },
      eventType: { type: "string" },
      status: enumString(["received", "processing", "processed", "failed", "ignored"]),
      attempts: { type: "integer" },
      nextAttemptAt: dateTime,
      processedAt: dateTime,
      lastError: { type: "string" },
    },
    ["provider", "merchantAccountId", "providerEventId", "eventType", "status", "attempts"],
  ),
  NotificationPreference: documentSchema(
    {
      recipientType: enumString(["user", "customer", "employee"]),
      recipientId: objectId,
      channels: { type: "object", additionalProperties: { type: "boolean" } },
      topics: { type: "object", additionalProperties: { type: "boolean" } },
      reminderLeadMinutes: arrayOf({ type: "integer" }),
      locale: { type: "string" },
      marketingConsentAt: dateTime,
      marketingConsentWithdrawnAt: dateTime,
    },
    ["recipientType", "recipientId", "channels", "topics", "reminderLeadMinutes", "locale"],
  ),
  PushSubscription: documentSchema(
    {
      userId: objectId,
      provider: enumString(["fcm", "apns", "web_push"]),
      platform: enumString(["web", "ios", "android"]),
      deviceId: { type: "string" },
      status: enumString(["active", "invalid", "revoked"]),
      lastSeenAt: dateTime,
      invalidatedAt: dateTime,
    },
    ["userId", "provider", "platform", "deviceId", "status", "lastSeenAt"],
  ),
  NotificationTemplate: documentSchema(
    { key: { type: "string" }, channel: enumString(["email", "sms", "whatsapp", "push"]), locale: { type: "string" }, subject: nullable({ type: "string" }), body: { type: "string" }, isActive: { type: "boolean" } },
    ["key", "channel", "locale", "body", "isActive"],
  ),
  Notification: documentSchema(
    {
      recipientType: enumString(["user", "customer", "employee"]),
      recipientId: objectId,
      bookingId: objectId,
      channel: enumString(["email", "sms", "whatsapp", "push"]),
      topic: enumString(["booking_update", "reminder", "waitlist_update", "staff_schedule", "marketing", "system"]),
      destination: { type: "string" },
      templateKey: { type: "string" },
      locale: { type: "string" },
      variables: { type: "object", additionalProperties: { type: "string" } },
      status: enumString(["queued", "processing", "sent", "failed", "cancelled"]),
      scheduledAt: dateTime,
      nextAttemptAt: dateTime,
      attempts: { type: "integer" },
      maxAttempts: { type: "integer" },
      providerMessageId: { type: "string" },
      sentAt: dateTime,
      lastError: { type: "string" },
    },
    ["recipientType", "recipientId", "channel", "topic", "destination", "templateKey", "locale", "variables", "status", "scheduledAt", "attempts", "maxAttempts"],
  ),
  ExternalConnector: documentSchema(
    {
      name: { type: "string" }, provider: { type: "string" }, type: enumString(["erp_pos", "crm", "calendar", "custom"]), scope: enumString(["business", "branch"]), branchId: nullable(objectId), status: enumString(["disabled", "active", "degraded", "revoked"]), baseUrl: nullable({ type: "string", format: "uri" }), secretReference: nullable({ type: "string", description: "Secret-manager reference; never the secret value." }), syncPolicies: arrayOf({ type: "object", additionalProperties: true }), pollingIntervalMinutes: nullable({ type: "integer" }), lastSuccessfulSyncAt: dateTime, lastSyncAttemptAt: dateTime, consecutiveFailures: { type: "integer" }, lastError: { type: "string" },
    },
    ["name", "provider", "type", "scope", "status", "syncPolicies", "consecutiveFailures"],
  ),
  ExternalEntityMapping: documentSchema(
    {
      connectorId: objectId, entityType: { type: "string" }, localId: objectId, externalId: { type: "string" }, origin: enumString(["local", "external"]), sourceOfTruth: enumString(["local", "external", "newest"]), externalVersion: nullable({ type: "string" }), localChecksum: nullable({ type: "string" }), externalChecksum: nullable({ type: "string" }), syncStatus: enumString(["pending", "synced", "conflict", "failed", "deleted_external"]), lastSyncedAt: dateTime, lastAttemptAt: dateTime, lastError: { type: "string" },
    },
    ["connectorId", "entityType", "localId", "externalId", "origin", "sourceOfTruth", "syncStatus"],
  ),
  IntegrationSyncJob: documentSchema(
    {
      jobId: { type: "string", format: "uuid" }, connectorId: objectId, direction: enumString(["inbound", "outbound"]), operation: enumString(["create", "update", "delete", "reconcile"]), entityType: { type: "string" }, localId: objectId, externalId: { type: "string" }, payload: { type: "object", additionalProperties: true }, status: enumString(["pending", "processing", "succeeded", "failed", "dead_letter"]), attempts: { type: "integer" }, maxAttempts: { type: "integer" }, nextAttemptAt: dateTime, completedAt: dateTime, lastError: { type: "string" },
    },
    ["jobId", "connectorId", "direction", "operation", "entityType", "status", "attempts", "maxAttempts"],
  ),
  AuditLog: {
    type: "object",
    properties: { _id: objectId, actorUserId: objectId, actorType: enumString(["user", "system", "integration"]), action: { type: "string" }, entityType: { type: "string" }, entityId: objectId, requestId: { type: "string" }, occurredAt: dateTime, createdAt: dateTime },
    required: ["_id", "actorType", "action", "entityType", "occurredAt", "createdAt"],
    additionalProperties: false,
  },
  OutboxEvent: documentSchema(
    { eventId: { type: "string", format: "uuid" }, aggregateType: { type: "string" }, aggregateId: objectId, eventType: { type: "string" }, payload: { type: "object", additionalProperties: true }, status: enumString(["pending", "processing", "published", "failed"]), attempts: { type: "integer" }, nextAttemptAt: dateTime, publishedAt: dateTime, lastError: { type: "string" } },
    ["eventId", "aggregateType", "aggregateId", "eventType", "payload", "status", "attempts"],
  ),
  EntityStatusResult: {
    type: "object",
    properties: {
      id: objectId,
      status: { type: "string" },
    },
    required: ["id", "status"],
    additionalProperties: false,
  },
  BookingLifecycleResult: {
    type: "object",
    properties: {
      id: objectId,
      reference: { type: "string" },
      status: enumString(["requested", "pending_advance", "confirmed", "checked_in", "in_progress", "completed", "cancelled", "no_show"]),
    },
    required: ["id", "reference", "status"],
    additionalProperties: false,
  },
  ExpirationResult: {
    type: "object",
    properties: { expired: { type: "integer", minimum: 0 } },
    required: ["expired"],
    additionalProperties: false,
  },
  ExternalSettlementResult: {
    type: "object",
    properties: {
      status: enumString(["not_tracked", "pending_external", "settled_external"]),
      externalReference: { type: "string" },
      externallyReportedFinalAmountMinor: { type: "integer", minimum: 0 },
      lastSyncedAt: dateTime,
      settledAt: dateTime,
    },
    required: ["status", "lastSyncedAt"],
    additionalProperties: false,
  },
  PaymentWebhookAccepted: {
    type: "object",
    properties: {
      eventId: objectId,
      provider: { type: "string" },
      providerEventId: { type: "string" },
      status: enumString(["received", "processing", "processed", "failed", "ignored"]),
    },
    required: ["eventId", "provider", "providerEventId", "status"],
    additionalProperties: false,
  },
  QuoteAcceptanceResult: {
    type: "object",
    properties: {
      quoteId: objectId,
      inquiryStatus: { type: "string", const: "accepted" },
      schedulingStatus: enumString(["booking_created", "staff_scheduling_required"]),
      booking: nullable(ref("Booking")),
      message: { type: "string" },
    },
    required: ["quoteId", "inquiryStatus", "schedulingStatus", "booking"],
    additionalProperties: false,
  },
  QuoteScheduleResult: {
    type: "object",
    properties: {
      schedulingStatus: { type: "string", const: "booking_created" },
      idempotentReplay: { type: "boolean" },
      booking: ref("Booking"),
    },
    required: ["schedulingStatus", "idempotentReplay", "booking"],
    additionalProperties: false,
  },
  Health: {
    type: "object",
    properties: { success: { type: "boolean", const: true }, status: { type: "string", const: "ok" }, timeZone: { type: "string" }, uptimeSeconds: { type: "integer", minimum: 0 } },
    required: ["success", "status", "timeZone", "uptimeSeconds"],
    additionalProperties: false,
  },
  Readiness: {
    type: "object",
    properties: { success: { type: "boolean" }, status: enumString(["ready", "not_ready"]), dependencies: { type: "object", properties: { mongodb: { type: "boolean" }, redis: { type: "boolean" } }, required: ["mongodb", "redis"], additionalProperties: false } },
    required: ["success", "status", "dependencies"],
    additionalProperties: false,
  },
};

export type ResponseSchemaName = keyof typeof responseSchemas;
